/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
  conceptsSidebar: [{ type: 'autogenerated', dirName: 'concepts' }],
  contractsSidebar: [{ type: 'autogenerated', dirName: 'contracts' }],
  sdkSidebar: [{ type: 'autogenerated', dirName: 'sdk' }],
  universalRouterLegacy: [
    {
      type: 'category',
      label: 'Universal Router (Legacy)',
      items: [
        { type: 'doc', id: 'universal-router-legacy/overview', label: 'Overview' },
        { type: 'doc', id: 'universal-router-legacy/technical-reference', label: 'Technical Reference' },
      ],
    },
  ],
}

module.exports = sidebars
