/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
  conceptsSidebar: [{ type: 'autogenerated', dirName: 'concepts' }],
  contractsSidebar: [{ type: 'autogenerated', dirName: 'contracts' }],
  sdkSidebar: [{ type: 'autogenerated', dirName: 'sdk' }],
}

module.exports = sidebars
