module.exports = {
  mySidebar: [
    {
      type: "category",
      label: "Concepts",
      items: [
        {
          type: "category",
          label: "Protocol Overview",
          items: [
            {
              type: "autogenerated",
              dirname: "./versioned_docs/version-V2/concepts/protocol-overview",
            },
          ],
        },
        {
          type: "category",
          label: "Core Concepts",
          items: [
            {
              type: "autogenerated",
              dirname: "./versioned_docs/version-V2/concepts/core-concepts",
            },
          ],
        },
        {
          type: "category",
          label: "Advanced Topics ",
          items: [
            {
              type: "autogenerated",
              dirname: "./versioned_docs/version-V2/concepts/advanced-topics",
            },
          ],
        },
        {
          type: "category",
          label: "Governance",
          items: [
            {
              type: "autogenerated",
              dirname: "./versioned_docs/version-V2/concepts/governance",
            },
          ],
        },
      ],
    },
  ],
};
