name: Lint

on: push

permissions: {}

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run linters
        run: yarn lint
