name: Check Benchmarks & Deploy
env:
  VERCEL_TEAM_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:

permissions: {}

jobs:
  check-uniswap-benchmarks:
    name: Check uniswap Benchmarks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn install

      - name: Check Licensure
        id: check_licensure
        run: yarn run check-licensure

      - name: Run Linter
        run: yarn lint

      - name: Check Type Correctness
        run: yarn run tsc --noEmit

      - name: Check Formatting
        run: yarn prettier --check .

  audit_with_lighthouse:
    name: Audit with Lighthouse
    runs-on: ubuntu-latest
    if: github.ref != 'refs/head/main' && github.ref != 'refs/heads/prod'
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: ./
    steps:
      # Step 1: Retrieve the Vercel Preview URL
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@e5fb141da2e3d62692b38e6c7c17477aad214165 # v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel_team_id: ${{ secrets.VERCEL_ORG_ID }}

      # Step 2: Wait for the Vercel deployment to be ready
      - uses: UnlyEd/github-action-await-vercel@3d536f03d951e603b21701814ba211dcbbafaf93 # v1
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ steps.vercel_preview_url.outputs.preview_url }}
          timeout: 420
          poll-interval: 15

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - name: Audit preview URL with Lighthouse (mobile)
        id: lighthouse_audit_mobile
        uses: treosh/lighthouse-ci-action@2e159d989f91bb9e399801b3e1ad90bcd4749f75 # v9
        with:
          urls: |
            https://${{ steps.vercel_preview_url.outputs.preview_url }}
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Audit preview URL with Lighthouse (desktop)
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@2e159d989f91bb9e399801b3e1ad90bcd4749f75 # v9
        with:
          urls: |
            https://${{ steps.vercel_preview_url.outputs.preview_url }}
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: .github/lighthouse/lighthouse-config.json

      - name: Format Lighthouse score
        id: format_lighthouse_score
        uses: actions/github-script@ffc2c79a5b2490bd33e0a41c1de74b877714d736 # v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const mobileLinks = ${{ steps.lighthouse_audit_mobile.outputs.links }};
            const mobileResult = ${{ steps.lighthouse_audit_mobile.outputs.manifest }}[0].summary;
            const desktopLinks = ${{ steps.lighthouse_audit.outputs.links }};
            const desktopResult = ${{ steps.lighthouse_audit.outputs.manifest }}[0].summary;
            const previewUrl = "https://${{ steps.vercel_preview_url.outputs.preview_url }}";
            const formatResult = (res) => Math.round((res * 100));
            const score = res => res >= 90 ? '🟢' : res >= 50 ? '🟠' : '🔴';
            Object.keys(mobileResult).forEach(key => mobileResult[key] = formatResult(mobileResult[key]));
            Object.keys(desktopResult).forEach(key => desktopResult[key] = formatResult(desktopResult[key]));
            const comment = [
              `## ⚡️ Lighthouse Report`,
              `### Mobile ([view report](${Object.values(mobileLinks)[0]}))`,
              '| Category | Score |',
              '| --- | --- |',
              `| ${score(mobileResult.performance)} Performance | ${mobileResult.performance} |`,
              `| ${score(mobileResult.accessibility)} Accessibility | ${mobileResult.accessibility} |`,
              `| ${score(mobileResult['best-practices'])} Best practices | ${mobileResult['best-practices']} |`,
              `| ${score(mobileResult.seo)} SEO | ${mobileResult.seo} |`,
              ` `,
              `### Desktop ([view report](${Object.values(desktopLinks)[0]}))`,
              '| Category | Score |',
              '| --- | --- |',
              `| ${score(desktopResult.performance)} Performance | ${desktopResult.performance} |`,
              `| ${score(desktopResult.accessibility)} Accessibility | ${desktopResult.accessibility} |`,
              `| ${score(desktopResult['best-practices'])} Best practices | ${desktopResult['best-practices']} |`,
              `| ${score(desktopResult.seo)} SEO | ${desktopResult.seo} |`,
              ` `,
              `*Lighthouse ran on [${previewUrl}](${previewUrl})*`
            ].join('\n');
            core.setOutput("comment", comment);
      - name: Add comment to PR
        uses: mshick/add-pr-comment@a96c578acba98b60f16c6866d5f20478dc4ef68b # v1
        with:
          message: |
            ${{ steps.format_lighthouse_score.outputs.comment }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
